api:
  identifier: 'anydev-autores'
  port: 3000

logger:
  options:
    level: trace

mongodb:
  url: 'mongodb://127.0.0.1:27017'
  database: 'backend'
  timeout: 10000
  options:
    useUnifiedTopology: true
    useNewUrlParser: true